#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---

# pkcs12 passwords
hashicorp_pkcs12_passphrase: Vaultpassword1
keycloak_pkcs12_passphrase: Keycloakpassword1

# application properties for Custos Core services
custos_core_grpc_port: 7071
custos_core_server_port: 8081
custos_core_spring_app_name: Custos-Core-Services-Server
custos_core_spring_zipkin_baseUrl: http://149.165.169.49:9411/
custos_core_spring_sleuth_sampler_probability: 1
custos_core_spring_main_allow_bean_definition_overriding: true
custos_core_management_security_enabled: false
custos_core_management_endpoints_web_exposure_include: "*"
custos_core_management_endpoint_metrics_enabled: true
custos_core_spring_jmx_enabled: true
custos_core_spring_datasource_url: jdbc:mysql://localhost:3306/core_services_server_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
custos_core_spring_datasource_username: root
custos_core_spring_datasource_password: Custosdatabase@1

## Hibernate Properties for Custos Core services
# The SQL dialect makes Hibernate generate better SQL for the chosen database
custos_core_spring_jpa_properties_hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
custos_core_spring_jpa_properties_hibernate_enable_lazy_load_no_trans: true
# Hibernate ddl auto (create, create-drop, validate, update)
custos_core_spring_jpa_hibernate_ddl_auto: update
custos_core_spring_profiles_active: dev
custos_core_logging_level_root: INFO

custos_core_ciLogon_admin_client_id: XXXX
custos_core_ciLogon_admin_client_secret: XXXX
custos_core_ciLogon_admin_auth_endpoint: https://test.cilogon.org/oauth2/oidc-cm

custos_core_iam_server_client_id: admin-cli
custos_core_iam_server_truststore_path: /home/ubuntu/keycloak-client-truststore.pkcs12
custos_core_iam_server_truststore_password: Keycloakpassword1
custos_core_iam_server_url: https://bm-dev-2.usecustos.org/auth/
custos_core_iam_server_admin_username: admin
custos_core_iam_server_admin_password: admin
custos_core_iam_server_super_admin_realm_id: master
custos_core_iam_federated_cilogon_authorization_endpoint: https://cilogon.org/authorize
custos_core_iam_federated_cilogon_token_endpoint: https://cilogon.org/oauth2/token
custos_core_iam_federated_cilogon_token_userinfo_endpoint: https://cilogon.org/oauth2/userinfo
custos_core_iam_federated_cilogon_issuer: https://cilogon.org
custos_core_iam_federated_cilogon_jwksUri: https://cilogon.org/oauth2/certs
custos_core_introspection_endpoint: https://{{ hostvars['custos'].ansible_host }}:32036/identity-management/v1.0.0/token/introspect
custos_core_issuer: https://{{ hostvars['custos'].ansible_host }}/
custos_core_authorization_endpoint: https://{{ hostvars['custos'].ansible_host }}/apiserver/identity-management/v1.0.0/authorize
custos_core_token_endpoint: https://{{ hostvars['custos'].ansible_host }}/apiserver/identity-management/v1.0.0/token
custos_core_end_session_endpoint: https://{{ hostvars['custos'].ansible_host }}/apiserver/identity-management/v1.0.0/logout
custos_core_user_info_endpoint: https://{{ hostvars['custos'].ansible_host }}/apiserver/user-management/v1.0.0/userinfo
custos_core_jwks_uri: https://{{ hostvars['custos'].ansible_host }}/apiserver/identity-management/v1.0.0/certs
custos_core_registration_endpoint: https://{{ hostvars['custos'].ansible_host }}/apiserver/tenant-management/v1.0.0/oauth2/tenant
custos_core_cluster_management_core_service_dns_name: cluster-management-core-service.keycloak.svc.cluster.local
custos_core_cluster_management_core_service_port: 7000

custos_core_services_server_hostname: localhost
custos_core_services_server_port: 7000

custos_core_custos_identity_auth_cache_enabled: true
custos_core_custos_identity_auth_cache_size: 1024

custos_core_core_messaging_service_broker_url: localhost:9092
custos_core_core_messaging_service_publisher_id: custosEventPublisher
custos_core_mail_smtp_auth: true
custos_core_mail_smtp_starttls_enable: true
custos_core_mail_smtp_host: smtp.gmail.com
custos_core_mail_smtp_port: 587
custos_core_mail_smtp_ssl_trust: smtp.gmail.com
custos_core_mail_sender_username: custosemailagent@gmail.com
custos_core_mail_sender_password: XXXXXX

custos_core_user_profile_core_service_dns_name: user-profile-core-service.custos.svc.cluster.local
custos_core_user_profile_core_service_port: 7000

# application properties for Custos Integration services
custos_int_grpc_port: 7070
custos_int_server_port: 8080
custos_int_spring_zipkin_baseUrl: http://149.165.169.49:9411/
custos_int_spring_application_name: custos-integrations-services-server
custos_int_spring_sleuth_sampler_probability: 1
custos_int_spring_main_allow_bean_definition_overriding: true
custos_int_management_security_enabled: false
custos_int_management_endpoints_web_exposure_include: "*"
custos_int_management_endpoint_metrics_enabled: true
custos_int_spring_jmx_enabled: true

custos_int_spring_profiles_active: dev
custos_int_logging_level_root: INFO

custos_int_core_services_server_port: 7071
custos_int_core_services_server_hostname: localhost
custos_int_iam_server_url: https://bm-dev-2.usecustos.org/auth//auth/
custos_int_tenant_base_uri: https://bm-dev-2.usecustos.org/auth/apiserver/tenant-management/v1.0.0/oauth2/tenant

# vault variables
vault_port: 443
vault_token: hvs.S8HfuwO0M46LIohBgAtKBTaR
vault_scheme: https
vault_host: "{{ hostvars['hashicorp'].ansible_host }}"
vault_uri: https://{{ hostvars['hashicorp'].ansible_host }}
spring_cloud_vault_ssl_truststore_password: Vaultpassword1
spring_cloud_vault_authentication: token
spring_cloud_vault_ssl_trust_store: file:/home/ubuntu/vault-client-truststore.pkcs12

# consul variables
consul_version: 1.7.1
consul_zip_file: consul_{{ consul_version }}_linux_amd64.zip
consul_install_dir: /usr/local/bin
consul_config_dir: /etc/consul
consul_data_dir: /var/data


active_profile: staging