#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
- name: Install MySQL
  apt:
    name:
    - mysql-server
    - python3-pymysql
  become: yes

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
#- name: update mysql root password for all root accounts
#  mysql_user: name=root host={{ item }} password={{ custos_core_spring_datasource_password }}
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost
- include: secure_install.yml
- include: create_db.yml
#
#- name: copy .my.cnf file with root password credentials
##  template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
#  copy:
#    src: templates/my.cnf.j2
#    dest: /root/.my.cnf
#    owner: root
#
#- name: delete anonymous MySQL server user for $server_hostname
#  action: mysql_user user="" host="{{ server_hostname }}" state="absent"
#
#- name: delete anonymous MySQL server user for localhost
#  action: mysql_user user="" state="absent"
#
#- name: remove the MySQL test database
#  action: mysql_db db=test state=absent

#- name: Create dynamic MySQL variables.
#  set_fact:
#    mysql_users:
#      - name: mycompany_user
#        host: "{{groups['database'][0]}}"
#        password: secret
#        priv: "*.*:SELECT"
#      - name: mycompany_user
#        host: "{{groups['database'][1]}}"
#        password: secret
#        priv: "*.*:SELECT"
#    mysql_replication_master: "{{groups['a4d.lamp.db.1'][0]}}"
