apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: custos.scigap.org
      http:
        paths:
          - path: /web/(/|$)(.*)
            backend:
              serviceName: resource-secret-management-service
              servicePort: envoyhttp
