apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: {{ .Values.deployment.clusterIssuer }}
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "${host}"
      http:
        paths:
          - path: /services(/|$)(.*)
            backend:
              serviceName: custos-integration-services-swagger
              servicePort: http

  tls:
    - hosts:
        - custos.scigap.org
      secretName: tls-services-secret