version: "3.3"
services:
    keycloak:
      image: quay.io/keycloak/keycloak:9.0.2
      ports:
        - "8443:8443"
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/test/certs/localhostcert.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/test/certs/localhostkey.pem
      volumes:
        - ./keycloak:/opt/keycloak/test/certs
    vault:
      image: vault:1.7.0
      container_name: vault
      restart: on-failure:10
      ports:
        - "8201:8201"
        - "8200:8200"
      environment:
        VAULT_ADDR: 'http://0.0.0.0:8201'
        VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"1"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
        VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
        VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
      cap_add:
        - IPC_LOCK
      healthcheck:
        test: "vault login 00000000-0000-0000-0000-000000000000 &&
                     vault kv get secret &&
                     vault secrets disable secret &&
                     vault secrets enable -version=1 -path=secret kv &&
                     vault secrets enable -version=1 -path=resourcesecret kv"
        interval: 5s
    rest-proxy:
      image: apachecustos/custos-rest-proxy:latest
      container_name: rest-proxy
      restart: on-failure:10
      ports:
        - "10000:50000"
    my_sql_local:
      container_name: my_sql_local
      image: mysql:8.0.31
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: core_services_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MAX_ALLOWED_PACKET: 1073741824
      command: --character-set-server=ucs2 --collation-server=ucs2_general_ci
#      volumes:
#        - ./init/mysql/scripts/bash:/docker-entrypoint-initdb.d
#        - ./init/mysql/scripts/sql:/tmp/sql
